from typing import Dict, List, Set

from pydantic import Field

from core.state import BaseInputState, BaseOutputState, BaseState
from models import (Issue, IssuesQueue, PlannedIssuesQueue, PlannedTaskQueue,
                    RequirementsDocument, TaskQueue)


class PlannerInput(BaseInputState):
    """
    PlannerInput defines the input data required for the planning process.

    Attributes:
        deliverable_list (List[str]): A list of deliverable descriptions that serve as inputs for task planning.
        issue_list (List[dict]): A list of issues to be processed during issue planning.
            (Note: Replace 'dict' with a dedicated Issue model if available.)
        requirements_document (RequirementsDocument): A detailed document containing both functional and non-functional
            requirements for the project.
        human_feedback (str): Feedback provided by a human reviewer that may include instructions for updating work packages.
        additional_information (str): Supplementary contextual information or system state details that augment the planning process.
        current_issue (Issue): The issue currently under review or analysis, which serves as the focus for issue planning.
    """
    deliverable_list: TaskQueue = Field(
        default_factory=list,
        description="List of deliverable descriptions for task planning."
    )
    issue_list: IssuesQueue = Field(
        default_factory=list,
        description="List of issues for issue planning. (Replace 'dict' with a dedicated Issue model if available.)"
    )
    requirements_document: RequirementsDocument = Field(
        description="A detailed document containing both functional and non-functional requirements for the project."
    )
    human_feedback: str = Field(
        default='',
        description="Feedback provided by a human reviewer, typically including instructions for updating work packages."
    )
    additional_information: str = Field(
        default='',
        description="Supplementary contextual information or system state details that augment the planning process."
    )
    current_issue: Issue = Field(
        default_factory=Issue,
        description="The issue currently under review or analysis, serving as the focus for issue planning."
    )


class PlannerOutput(BaseOutputState):
    """
    PlannerOutput defines the output data produced by the planning process.

    Attributes:
        planned_tasks (PlannedTaskQueue): A queue containing the work packages (tasks) generated by the planner.
        planned_issues (PlannedIssuesQueue): A queue containing the issues processed and planned by the planner.
        current_issue (Issue): The issue that was under review or analysis during planning.
    """
    planned_tasks: PlannedTaskQueue = Field(
        default_factory=PlannedTaskQueue,
        description="Queue of work packages (tasks) generated by the planner."
    )
    planned_issues: PlannedIssuesQueue = Field(
        default_factory=PlannedIssuesQueue,
        description="Queue of planned issues produced by the planner."
    )
    current_issue: Issue = Field(
        default_factory=Issue,
        description="The issue that was under review or analysis during the planning process."
    )


class PlannerState(BaseState):
    """
    PlannerState maintains the comprehensive state of the planning process.

    This state is used to track inputs, outputs, and internal progress for both task and issue planning.
    It includes a unified file mapping for work packages, as well as bookkeeping for processed items and file generation.

    Attributes:
        deliverable_list (List[str]): A list of deliverable descriptions used for task planning.
        issue_list (List[dict]): A list of issues used for issue planning.
        processed_item_ids (Set[str]): A set of deliverable or issue IDs that have been processed by the planner.
        requirements_document (RequirementsDocument): The requirements document detailing project specifications.
        human_feedback (str): Feedback provided by a human reviewer to update work packages.
        additional_information (str): Supplementary contextual data or system state details that support the planning process.
        current_issue (Issue): The issue currently under review or analysis.
        planned_tasks (PlannedTaskQueue): A queue containing the work packages (tasks) generated by the planner.
        planned_issues (PlannedIssuesQueue): A queue containing the planned issues produced by the planner.
        file_count (int): The total number of work package files generated so far.
        planned_backlogs (Dict[str, str]): A mapping where each key is a parent deliverable ID and the corresponding value is the planned backlog content.
    """
    deliverable_list: TaskQueue = Field(
        default_factory=list,
        description="List of deliverable descriptions for task planning."
    )
    issue_list: IssuesQueue = Field(
        default_factory=list,
        description="List of issues for issue planning."
    )
    processed_item_ids: Set[str] = Field(
        default_factory=set,
        description="Set of deliverable or issue IDs that have already been processed by the planner."
    )
    requirements_document: RequirementsDocument = Field(
        default_factory=RequirementsDocument,
        description="The requirements document detailing the project specifications."
    )
    human_feedback: str = Field(
        default='',
        description="Feedback provided by a human reviewer to update work packages."
    )
    additional_information: str = Field(
        default='',
        description="Supplementary contextual information or system state details that support the planning process."
    )
    current_issue: Issue = Field(
        default_factory=Issue,
        description="The issue currently under review or analysis."
    )
    planned_tasks: PlannedTaskQueue = Field(
        default_factory=PlannedTaskQueue,
        description="Queue of work packages (tasks) generated by the planner."
    )
    planned_issues: PlannedIssuesQueue = Field(
        default_factory=PlannedIssuesQueue,
        description="Queue of planned issues produced by the planner."
    )
    planned_backlogs: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Mapping of planned backlogs where keys are parent deliverable IDs and values are the corresponding backlog content."
    )
