"""
This module provides a FS class with a method to write generated code to a specified file.
"""

from langchain.tools import tool

from typing import Annotated

import os

class CodeFileWriter:
    """
    This class provides a method to write generated code to a specified file.
    """
    
    @tool
    def write_generated_code_to_file(
        generated_code: Annotated[
            str, 
            "The string of code that was generated by the agent. This code will be written to a file."
        ],
        file_path: Annotated[
            str, 
            "The absolute path, including the filename and extension, where the generated code will be written. If the directory does not exist, it will be created."
        ]
    ) -> tuple[bool, str]:
        """
        Writes the provided generated code to the specified file.

        Args:
            generated_code (str): The string of code that was generated by the agent. 
            This code will be written to a file.
            file_path (str): The absolute path, including the filename and extension, 
            where the generated code will be written. If the directory does not exist, 
            it will be created.

        Returns:
            tuple: A tuple containing a boolean and a string. The boolean indicates 
            whether an error occurred (True if an error occurred, False otherwise). 
            The string provides a detailed message, either indicating the successful 
            writing of the generated code to the specified file or describing the 
            error that occurred.
        """

        try:
            # Ensure the directory exists before writing the file
            os.makedirs(os.path.dirname(file_path), exist_ok=True)
            
            with open(file_path, 'w') as file:
                file.write(generated_code)
            
            return (False, f"Success! The generated code was written to the following location: '{file_path}'.")
        except BaseException as e:
            return (True, f"An error occurred while attempting to write the generated code to the file. Here's what went wrong: '{repr(e)}'.")
        