from langchain.tools import tool

from typing import Annotated

import os

class FS:

    @tool
    def write_generated_code_to_file(
        generated_code: Annotated[str, "The code generated by the agent."],
        file_path: Annotated[str, "Absolute path where the generated code should be written can handle directory create if does not exist."]
    ) -> tuple[bool, str]:
        """
        Writes the provided generated code to the specified file within the project structure.

        Args:
            generated_code (str): The code generated by the agent.
            file_path (str): The path where the generated code should be written.
        """
        try:

            # Ensure the directory exists before writing the file
            os.makedirs(os.path.dirname(file_path), exist_ok=True)
            
            with open(file_path, 'w') as file:
                file.write(generated_code)
            
            return (False, f"Successfully wrote the generated code to: {file_path}")
        except BaseException as e:
            return (True, f"Failed to write generated code. Error: {repr(e)}")
        