""" Graph State for PM Agent """
from typing import Annotated, Dict, List, TypedDict

from pydantic import Field

from core.state import BaseInputState, BaseOutputState, BaseState
from models.coder_models import CodeGenerationPlan
from models.constants import PStatus
from models.models import (Issue, IssuesQueue, PlannedIssue,
                           PlannedIssuesQueue, PlannedTask, PlannedTaskQueue,
                           RequirementsDocument, Task, TaskQueue)
from models.tests_generator_models import FileFunctionSignatures


class SupervisorInput(BaseInputState):
    """ Input State for Supervisor """
    project_id: int = Field(
        description="Unique identifier of the project associated with the supervisor task."
    )
    microservice_id: int = Field(
        description="Unique identifier of the microservice being managed."
    )
    license_header: str = Field(
        description="Text of the license header to prepend to each generated file."
    )
    license_url: str = Field(
        description="URL where the full license text can be retrieved."
    )


class SupervisorOuptut(BaseOutputState):
    """ Output State for Supervisor """
    microservice_name: str = Field(
        description="Name of the microservice suggested by Architect"
    )
    agents_status: str = Field(
        description="Current operational status of the agent assigned to the project."
    )
    current_task: Task = Field(
        default_factory=Task,
        description="Details of the task that is currently in progress."
    )
    current_planned_task: PlannedTask = Field(
        default_factory=PlannedTask,
        description="Details of the task that has been planned for upcoming execution."
    )
    current_issue: Issue = Field(
        default_factory=Issue,
        description="Information regarding the issue currently being addressed."
    )
    current_planned_issue: PlannedIssue = Field(
        default_factory=PlannedIssue,
        description="Information regarding the issue that is planned for future resolution."
    )
    issues: IssuesQueue = Field(
        default_factory=IssuesQueue,
        description="Queue of issues identified during project review."
    )
    tasks: TaskQueue = Field(
        default_factory=TaskQueue,
        description="Queue of tasks generated during the project development process."
    )
    human_feedback: List[tuple[str, str]] = Field(
        default_factory=list,
        description="List of tuples capturing human feedback during the human-in-the-loop process."
    )
    functions_skeleton: FileFunctionSignatures = Field(
        default_factory=FileFunctionSignatures,
        description="Skeleton definitions for functions generated by the supervisor."
    )
    test_code: Dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of filenames to their corresponding generated test code."
    )
    planned_tasks: PlannedTaskQueue = Field(
        default_factory=PlannedIssuesQueue,
        description="Queue of planned tasks representing future work packages."
    )
    planned_issues: PlannedIssuesQueue = Field(
        default_factory=PlannedIssuesQueue,
        description="Queue of issues planned for upcoming resolution."
    )
    requirements_document: RequirementsDocument = Field(
        default_factory=RequirementsDocument,
        description="Document outlining the detailed requirements and specifications for the project."
    )
    code_generation_plan_list: List[CodeGenerationPlan] = Field(
        default_factory=list,
        description="List of plans detailing the approach for generating code."
    )


class SupervisorState(BaseState):
    """State of the supervisor."""
    project_id: int = Field(
        default=-1,
        description="Unique identifier of the project (default -1 indicates an uninitialized state)."
    )
    microservice_id: int = Field(
        default=-1,
        description="Unique identifier of the microservice (default -1 indicates an uninitialized state)."
    )
    license_header: str = Field(
        default="",
        description="License header text to be inserted at the top of each generated file."
    )
    license_url: str = Field(
        default="",
        description="URL from which the full license text can be obtained."
    )
    microservice_name: str = Field(
        default="",
        description="Name of the microservice suggested by architect."
    )
    agents_status: str = Field(
        default="",
        description="Current operational status of the project agent."
    )
    current_task: Task = Field(
        default_factory=Task,
        description="Details of the task that is currently being executed."
    )
    current_planned_task: PlannedTask = Field(
        default_factory=PlannedTask,
        description="Details of the next planned task in the workflow."
    )
    current_issue: Issue = Field(
        default_factory=Issue,
        description="Information regarding the issue currently being addressed."
    )
    current_planned_issue: PlannedIssue = Field(
        default_factory=PlannedIssue,
        description="Information regarding the next issue planned for resolution."
    )
    issues: IssuesQueue = Field(
        default_factory=IssuesQueue,
        description="Queue containing issues reported or discovered during project execution."
    )
    tasks: TaskQueue = Field(
        default_factory=TaskQueue,
        description="Queue containing tasks generated throughout the project lifecycle."
    )
    human_feedback: List[tuple[str, str]] = Field(
        default_factory=list,
        description="List of tuples representing human feedback entries for manual review and adjustments."
    )
    functions_skeleton: FileFunctionSignatures = Field(
        default_factory=FileFunctionSignatures,
        description="Skeleton definitions of functions to be generated as part of the project codebase."
    )
    test_code: Dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of filenames to their generated test code snippets."
    )
    planned_tasks: PlannedTaskQueue = Field(
        default_factory=PlannedIssuesQueue,
        description="Queue of planned tasks representing upcoming work packages."
    )
    planned_issues: PlannedIssuesQueue = Field(
        default_factory=PlannedIssuesQueue,
        description="Queue of issues that have been planned for future resolution."
    )
    requirements_document: RequirementsDocument = Field(
        default_factory=RequirementsDocument,
        description="Detailed document outlining the project's requirements and specifications."
    )
    code_generation_plan_list: List[CodeGenerationPlan] = Field(
        default_factory=list,
        description="List of code generation plans outlining the approach and strategy for code creation."
    )


class SupervisorState1(TypedDict):
    """
    Represents the state of Project Manager to maintain the project level information
    and status.
    """

    # @out
    is_rag_query_answered: Annotated[
        bool,
        BaseState.out_field("Indicates whether the RAG agent has answered the query.")
    ]

    # @out
    rag_cache_queries: Annotated[
        List[str],
        BaseState.out_field("Queries generated for the RAG cache.")
    ]

    # @out
    rag_retrieval: Annotated[
        str,
        BaseState.out_field("The RAG retrieved data.")
    ]

    # @internal
    previous_project_status: Annotated[
        PStatus,
        BaseState.internal_field("The status of the previous project.")
    ]

    # @internal
    rag_cache_building: Annotated[
        str,
        BaseState.internal_field(
            "Holds the questions and answers related to the cache building queries."
        )
    ]

    # @internal
    is_rag_cache_created: Annotated[
        bool,
        BaseState.internal_field(
            "Indicates whether the RAG cache has been created. This is a "
            "single-time update."
        )
    ]

    # @internal
    is_initial_additional_info_ready: Annotated[
        bool,
        BaseState.internal_field(
            "Indicates whether the initial additional information is ready. "
            "This is set once."
        )
    ]

    # @internal
    are_requirements_prepared: Annotated[
        bool,
        BaseState.internal_field(
            "Indicates whether the requirements have been prepared. "
            "This is a single-time update."
        )
    ]

    # @internal
    are_planned_tasks_in_progress: Annotated[
        bool,
        BaseState.internal_field(
            "Indicates whether any planned tasks are currently in progress. "
            "This flag is managed by the supervisor:\n"
            "- Set to True when the planner breaks down larger tasks into smaller planned tasks.\n"
            "- Set to False when the planned tasks list is empty.\n"
            "The flag is used to control a loop that operates while planned tasks are being created and processed."
        )
    ]

    # @internal
    are_planned_issues_in_progress: Annotated[
        bool,
        BaseState.internal_field(
            "Indicates whether any planned issues are currently in progress. "
            "This flag is managed by the supervisor:\n"
            "- Set to True when the planner breaks down larger issues into smaller planned issues.\n"
            "- Set to False when the planned issues list is empty.\n"
            "The flag is used to control a loop that operates while planned issues are being created and processed."
        )
    ]

    # @internal
    is_human_reviewed: Annotated[
        bool,
        BaseState.internal_field(
            "Indicates whether the human review has been completed."
        )
    ]
