from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict, Field

from core.state import BaseOutputState, BaseState
from models.coder_models import CodeGenerationPlan
from models.constants import PStatus
from models.models import (Issue, IssuesQueue, PlannedIssue,
                           PlannedIssuesQueue, PlannedTask, PlannedTaskQueue,
                           RequirementsDocument, Task, TaskQueue)


class SupervisorInput(BaseModel):
    """ Input State for Supervisor """
    model_config = ConfigDict(
        extra='forbid',
        arbitrary_types_allowed = True,
    )

    user_prompt: str = Field(
        description="The user's original prompt for code generation."
    )
    project_directory: str = Field(
        description="The absolute path where the generated project will be saved."
    )
    project_id: int = Field(
        description="Unique identifier of the project associated with the supervisor task."
    )
    microservice_id: int = Field(
        description="Unique identifier of the microservice being managed."
    )
    license_header: str = Field(
        description="Text of the license header to prepend to each generated file."
    )
    license_url: str = Field(
        description="URL where the full license text can be retrieved."
    )

def _default_planned_issue() -> PlannedIssue:
    return PlannedIssue(is_function_generation_required=False)


class SupervisorOuptut(BaseOutputState):
    """ Output State for Supervisor """
    microservice_name: str = Field(
        description="Name of the microservice suggested by Architect"
    )
    project_status: PStatus = Field(
        description="The current status of the project."
    )
    agents_status: str = Field(
        description="Current operational status of the agent assigned to the project."
    )
    current_task: Task = Field(
        default_factory=Task,
        description="Details of the task that is currently in progress."
    )
    current_planned_task: PlannedTask = Field(
        default_factory=PlannedTask,
        description="Details of the task that has been planned for upcoming execution."
    )
    current_issue: Issue = Field(
        default_factory=Issue,
        description="Information regarding the issue currently being addressed."
    )
    current_planned_issue: PlannedIssue = Field(
        default_factory=_default_planned_issue,
        description="Information regarding the issue that is planned for future resolution."
    )
    issues: IssuesQueue = Field(
        default_factory=IssuesQueue,
        description="Queue of issues identified during project review."
    )
    tasks: TaskQueue = Field(
        default_factory=TaskQueue,
        description="Queue of tasks generated during the project development process."
    )
    human_feedback: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="List of tuples capturing human feedback during the human-in-the-loop process."
    )
    functions_skeleton: Dict[str, Any] = Field(
        default_factory=dict,
        description="Skeleton definitions for functions generated by the supervisor."
    )
    test_code: Dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of filenames to their corresponding generated test code."
    )
    planned_tasks: PlannedTaskQueue = Field(
        default_factory=PlannedTaskQueue,
        description="Queue of planned tasks representing future work packages."
    )
    planned_issues: PlannedIssuesQueue = Field(
        default_factory=PlannedIssuesQueue,
        description="Queue of issues planned for upcoming resolution."
    )
    requirements_document: RequirementsDocument = Field(
        default_factory=RequirementsDocument,
        description="Document outlining the detailed requirements and specifications for the project."
    )
    code_generation_plan_list: List[CodeGenerationPlan] = Field(
        default_factory=list,
        description="List of plans detailing the approach for generating code."
    )


class SupervisorState(BaseState):
    """State of the supervisor."""
    project_id: int = Field(
        default=-1,
        description="Unique identifier of the project (default -1 indicates an uninitialized state)."
    )
    microservice_id: int = Field(
        default=-1,
        description="Unique identifier of the microservice (default -1 indicates an uninitialized state)."
    )
    project_status: PStatus = Field(
        default=PStatus.RECEIVED,
        description="The current status of the project."
    )
    license_header: str = Field(
        default="",
        description="License header text to be inserted at the top of each generated file."
    )
    license_url: str = Field(
        default="",
        description="URL from which the full license text can be obtained."
    )
    microservice_name: str = Field(
        default="",
        description="Name of the microservice suggested by architect."
    )
    agents_status: str = Field(
        default="",
        description="Current operational status of the project agent."
    )
    current_task: Task = Field(
        default_factory=Task,
        description="Details of the task that is currently being executed."
    )
    current_planned_task: PlannedTask = Field(
        default_factory=PlannedTask,
        description="Details of the next planned task in the workflow."
    )
    current_issue: Issue = Field(
        default_factory=Issue,
        description="Information regarding the issue currently being addressed."
    )
    current_planned_issue: PlannedIssue = Field(
        default_factory=_default_planned_issue,
        description="Information regarding the next issue planned for resolution."
    )
    issues: IssuesQueue = Field(
        default_factory=IssuesQueue,
        description="Queue containing issues reported or discovered during project execution."
    )
    tasks: TaskQueue = Field(
        default_factory=TaskQueue,
        description="Queue containing tasks generated throughout the project lifecycle."
    )
    human_feedback: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="List of tuples representing human feedback entries for manual review and adjustments."
    )
    functions_skeleton: Dict[str, Any] = Field(
        default_factory=dict,
        description="Skeleton definitions of functions to be generated as part of the project codebase."
    )
    test_code: Dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of filenames to their generated test code snippets."
    )
    planned_tasks: PlannedTaskQueue = Field(
        default_factory=PlannedTaskQueue,
        description="Queue of planned tasks representing upcoming work packages."
    )
    planned_issues: PlannedIssuesQueue = Field(
        default_factory=PlannedIssuesQueue,
        description="Queue of issues that have been planned for future resolution."
    )
    requirements_document: RequirementsDocument = Field(
        default_factory=RequirementsDocument,
        description="Detailed document outlining the project's requirements and specifications."
    )
    code_generation_plan_list: List[CodeGenerationPlan] = Field(
        default_factory=list,
        description="List of code generation plans outlining the approach and strategy for code creation."
    )

    # @internal
    are_planned_tasks_in_progress: bool = Field(
        default=False,
        description=(
            "Indicates whether any planned tasks are currently in progress. "
            "This flag is managed by the supervisor:\n"
            "- Set to True when the planner breaks down larger tasks into smaller planned tasks.\n"
            "- Set to False when the planned tasks list is empty.\n"
            "The flag is used to control a loop that operates while planned tasks are being created and processed."
        )
    )
    are_planned_issues_in_progress: bool = Field(
        default=False,
        description=(
            "Indicates whether any planned issues are currently in progress. "
            "This flag is managed by the supervisor:\n"
            "- Set to True when the planner breaks down larger issues into smaller planned issues.\n"
            "- Set to False when the planned issues list is empty.\n"
            "The flag is used to control a loop that operates while planned issues are being created and processed."
        )
    )
    is_human_reviewed: bool = Field(
        default=False,
        description="Indicates whether the human review has been completed."
    )
    # Will be used during the call_human
    previous_project_status: PStatus = Field(
        default=PStatus.NONE,
        description="Stores the previous project status, representing the state of the project prior to the current update. Defaults to PStatus.NONE if no previous status exists."
    )
